-- Consolidated initial migration (merged V1..V6)
-- This migration creates plural table names and final schema for PostgreSQL

-- Create enum types
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gender_enum') THEN
        CREATE TYPE gender_enum AS ENUM ('MALE', 'FEMALE', 'OTHER');
    END IF;
END$$;

-- categories --
CREATE TABLE categories
(
    id            integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)       NOT NULL UNIQUE,
    description   VARCHAR(255)       NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

-- users --
CREATE TABLE users
(
    id             VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NULL,
    password       VARCHAR(255) NOT NULL,
    first_name     VARCHAR(255) NULL,
    last_name      VARCHAR(255) NULL,
    dob            DATE     NULL,
    gender         gender_enum DEFAULT 'OTHER',
    phone_number   VARCHAR(255) NULL,
    created_at     timestamptz DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- roles --
CREATE TABLE roles
(
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(255) NULL,
    CONSTRAINT pk_roles PRIMARY KEY (name)
);

-- user_roles --
CREATE TABLE user_roles
(
    role_name VARCHAR(255) NOT NULL,
    user_id   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_name)
);

-- courses --
CREATE TABLE courses
(
    id            VARCHAR(255) NOT NULL,
    title         VARCHAR(255) NULL,
    image_url     VARCHAR(255) NULL,
    published     boolean       NULL,
    instructor_id VARCHAR(255) NULL,
    price         numeric(15,2)       NULL,
    discount      INT          NULL,
    long_desc     TEXT         NULL,
    short_desc    VARCHAR(255) NULL,
    category_id   INT          NULL,
    level         VARCHAR(255) NULL,
    created_at    timestamptz     NULL,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

-- lessons --
CREATE TABLE lessons
(
    id            VARCHAR(255) NOT NULL,
    title         VARCHAR(255) NULL,
    lesson_key    VARCHAR(255) NULL,
    video_url     VARCHAR(255) NULL,
    description   TEXT         NULL,
    duration      BIGINT       NOT NULL,
    course_id     VARCHAR(255) NULL,
    created_at    timestamptz  NULL,
    is_preview    BOOLEAN NOT NULL DEFAULT FALSE,
    status        VARCHAR(255) NULL,
    CONSTRAINT pk_lessons PRIMARY KEY (id)

);

-- objectives --
CREATE TABLE objectives
(
    id            VARCHAR(255) NOT NULL,
    description   VARCHAR(255) NULL,
    course_id     VARCHAR(255) NULL,
    CONSTRAINT pk_objectives PRIMARY KEY (id)
);

-- course_requirements --
CREATE TABLE course_requirements
(
    id            VARCHAR(255) NOT NULL,
    description   VARCHAR(255) NULL,
    course_id     VARCHAR(255) NULL,
    CONSTRAINT pk_course_requirements PRIMARY KEY (id)
);

-- registers --
CREATE TABLE registers
(
    id            VARCHAR(255) NOT NULL,
    student_id    VARCHAR(255) NULL,
    course_id     VARCHAR(255) NULL,
    price         numeric(15,2)        NULL,
    register_date timestamptz     NULL,
    CONSTRAINT pk_registers PRIMARY KEY (id)
);

-- instructor_profiles --
CREATE TABLE instructor_profiles
(
    user_id       VARCHAR(255) NOT NULL,
    bio           TEXT         NULL,
    bank_name     VARCHAR(255),
    account_number VARCHAR(255),
    account_name  VARCHAR(255),
    CONSTRAINT pk_instructor_profiles PRIMARY KEY (user_id)
);

-- instructor_statistics --
CREATE TABLE instructor_statistics
(
    id                  VARCHAR(255) NOT NULL,
    month               INT          NOT NULL,
    year                INT          NOT NULL,
    total_registrations INT          NOT NULL,
    total_earnings      numeric(15,2)        NOT NULL,
    instructor_id       VARCHAR(255) NULL,
    CONSTRAINT pk_instructor_statistics PRIMARY KEY (id)
);

-- instructor_payments --
CREATE TABLE instructor_payments
(
    id           VARCHAR(255) NOT NULL,
    statistic_id VARCHAR(255) NOT NULL,
    paid_at      timestamptz     NULL,
    CONSTRAINT pk_instructor_payments PRIMARY KEY (id)
);

-- invalid_tokens --
CREATE TABLE invalid_tokens
(
    id         VARCHAR(255) NOT NULL,
    expiration timestamptz     NULL,
    CONSTRAINT pk_invalid_tokens PRIMARY KEY (id)
);

-- lesson_progresses --
CREATE TABLE lesson_progresses (
    id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    lesson_id VARCHAR(255) NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    watched_time BIGINT NOT NULL DEFAULT 0,
    updated_at timestamptz,
    CONSTRAINT pk_lesson_progresses PRIMARY KEY (id)
);

-- Constraints / Foreign Keys
ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_role FOREIGN KEY (role_name) REFERENCES roles (name);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE course_requirements
    ADD CONSTRAINT fk_course_requirements_course FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE registers
    ADD CONSTRAINT fk_registers_course FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE registers
    ADD CONSTRAINT fk_registers_student FOREIGN KEY (student_id) REFERENCES users (id);

ALTER TABLE objectives
    ADD CONSTRAINT fk_objectives_course FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE lessons
    ADD CONSTRAINT fk_lessons_course FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE instructor_statistics
    ADD CONSTRAINT fk_instructor_statistics_instructor FOREIGN KEY (instructor_id) REFERENCES users (id);

ALTER TABLE instructor_payments
    ADD CONSTRAINT uc_instructor_payments_statistic UNIQUE (statistic_id);

ALTER TABLE instructor_payments
    ADD CONSTRAINT fk_instructor_payments_statistic FOREIGN KEY (statistic_id) REFERENCES instructor_statistics (id);

ALTER TABLE courses
    ADD CONSTRAINT fk_courses_category FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE courses
    ADD CONSTRAINT fk_courses_instructor FOREIGN KEY (instructor_id) REFERENCES users (id);

ALTER TABLE instructor_profiles
    ADD CONSTRAINT fk_instructor_profiles_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE lesson_progresses
    ADD CONSTRAINT fk_lesson_progresses_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE lesson_progresses
    ADD CONSTRAINT fk_lesson_progresses_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id);

-- End of consolidated migration
