# spring boot
#spring.application.name=online_learning
#spring.profiles.active=dev

# server
server.port=8080
server.servlet.context-path=/online_learning

# JPA / Hibernate (if using Spring Data JPA)
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true



# Config JWT (JSON Web Token)
jwt.singerKey=${JWT_SINGER_KEY}
jwt.valid-duration=100000
jwt.refresh-duration=1200

# Config Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.database=${REDIS_DATABASE:0}
spring.data.redis.timeout=2s
auth.blacklist.prefix=${AUTH_BLACKLIST_PREFIX:auth:blacklist:}

# config zalopay
zalopay.baseUrl=${ZALOPAY_BASE_URL}
zalopay.key1=${ZALOPAY_KEY_1}
zalopay.key2=${ZALOPAY_KEY_2}
zalopay.appId=${ZALOPAY_APP_ID}
zalopay.endPoint=${ZALOPAY_END_POINT}
zalopay.callbackUrl=${ZALOPAY_CALLBACK_URL}
zalopay.redirectUrl=${ZALOPAY_REDIRECT_URL}

# config file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1200MB
spring.servlet.multipart.max-request-size=1200MB

# config ffprobe
ffmpeg.path=D:\\download\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffprobe.exe

frontend_url=${FRONTEND_URL}

storage.provider=${STORAGE_PROVIDER}
# R2 configuration
r2.accessKey=${R2_ACCESS_KEY}
r2.secretKey=${R2_SECRET_KEY}
r2.region=${R2_REGION}
r2.endpoint=${R2_ENDPOINT}
r2.imageBucketName=${R2_IMAGE_BUCKET_NAME}
r2.videoBucketName=${R2_VIDEO_BUCKET_NAME}
r2.publicUrl=${R2_PUBLIC_URL}
# Config AWS (Amazon Web Services)
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.videoBucketName=${AWS_VIDEO_BUCKET_NAME}
aws.imageBucketName=${AWS_IMAGE_BUCKET_NAME}


