# ========================
# DATABASE - DEV
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/online_learning_db
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

# ========================
# REDIS - DEV
# ========================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=2s

# ========================
# OPENAPI - DEV
# ========================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true