# ========================
# DATABASE - PROD
# ========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false

# ========================
# REDIS - PROD
# ========================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.database=${REDIS_DATABASE:0}
spring.data.redis.timeout=2s

# ========================
# OPENAPI - PROD
# ========================
springdoc.api-docs.enabled=${OPENAPI_DOCS_ENABLED:false}
springdoc.swagger-ui.enabled=${OPENAPI_SWAGGER_UI_ENABLED:false}
